/* 
 * ws-treasure
 *
 * tresure api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateManyPartnerDto
    /// </summary>
    [DataContract]
        public partial class CreateManyPartnerDto :  IEquatable<CreateManyPartnerDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateManyPartnerDto" /> class.
        /// </summary>
        /// <param name="bulk">bulk (required).</param>
        public CreateManyPartnerDto(List<Partner> bulk = default(List<Partner>))
        {
            // to ensure "bulk" is required (not null)
            if (bulk == null)
            {
                throw new InvalidDataException("bulk is a required property for CreateManyPartnerDto and cannot be null");
            }
            else
            {
                this.Bulk = bulk;
            }
        }
        
        /// <summary>
        /// Gets or Sets Bulk
        /// </summary>
        [DataMember(Name="bulk", EmitDefaultValue=false)]
        public List<Partner> Bulk { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateManyPartnerDto {\n");
            sb.Append("  Bulk: ").Append(Bulk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateManyPartnerDto);
        }

        /// <summary>
        /// Returns true if CreateManyPartnerDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateManyPartnerDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateManyPartnerDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Bulk == input.Bulk ||
                    this.Bulk != null &&
                    input.Bulk != null &&
                    this.Bulk.SequenceEqual(input.Bulk)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Bulk != null)
                    hashCode = hashCode * 59 + this.Bulk.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
