/* 
 * ws-treasure
 *
 * tresure api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Coupon
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CouponTests
    {
        // TODO uncomment below to declare an instance variable for Coupon
        //private Coupon instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Coupon
            //instance = new Coupon();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Coupon
        /// </summary>
        [Test]
        public void CouponInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Coupon
            //Assert.IsInstanceOfType<Coupon> (instance, "variable 'instance' is a Coupon");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'ExpireDate'
        /// </summary>
        [Test]
        public void ExpireDateTest()
        {
            // TODO unit test for the property 'ExpireDate'
        }
        /// <summary>
        /// Test the property 'ValidatedAt'
        /// </summary>
        [Test]
        public void ValidatedAtTest()
        {
            // TODO unit test for the property 'ValidatedAt'
        }
        /// <summary>
        /// Test the property 'Partner'
        /// </summary>
        [Test]
        public void PartnerTest()
        {
            // TODO unit test for the property 'Partner'
        }
        /// <summary>
        /// Test the property 'OpenTreasure'
        /// </summary>
        [Test]
        public void OpenTreasureTest()
        {
            // TODO unit test for the property 'OpenTreasure'
        }

    }

}
