/* 
 * ws-treasure
 *
 * tresure api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateManyOpenTreasureDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateManyOpenTreasureDtoTests
    {
        // TODO uncomment below to declare an instance variable for CreateManyOpenTreasureDto
        //private CreateManyOpenTreasureDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateManyOpenTreasureDto
            //instance = new CreateManyOpenTreasureDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateManyOpenTreasureDto
        /// </summary>
        [Test]
        public void CreateManyOpenTreasureDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateManyOpenTreasureDto
            //Assert.IsInstanceOfType<CreateManyOpenTreasureDto> (instance, "variable 'instance' is a CreateManyOpenTreasureDto");
        }


        /// <summary>
        /// Test the property 'Bulk'
        /// </summary>
        [Test]
        public void BulkTest()
        {
            // TODO unit test for the property 'Bulk'
        }

    }

}
