/* 
 * ws-treasure
 *
 * tresure api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OneOfinlineResponse2004
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfinlineResponse2004Tests
    {
        // TODO uncomment below to declare an instance variable for OneOfinlineResponse2004
        //private OneOfinlineResponse2004 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfinlineResponse2004
            //instance = new OneOfinlineResponse2004();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfinlineResponse2004
        /// </summary>
        [Test]
        public void OneOfinlineResponse2004InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfinlineResponse2004
            //Assert.IsInstanceOfType<OneOfinlineResponse2004> (instance, "variable 'instance' is a OneOfinlineResponse2004");
        }



    }

}
