/* 
 * ws-treasure
 *
 * tresure api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Partner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PartnerTests
    {
        // TODO uncomment below to declare an instance variable for Partner
        //private Partner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Partner
            //instance = new Partner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Partner
        /// </summary>
        [Test]
        public void PartnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Partner
            //Assert.IsInstanceOfType<Partner> (instance, "variable 'instance' is a Partner");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Floor'
        /// </summary>
        [Test]
        public void FloorTest()
        {
            // TODO unit test for the property 'Floor'
        }
        /// <summary>
        /// Test the property 'ShopNumber'
        /// </summary>
        [Test]
        public void ShopNumberTest()
        {
            // TODO unit test for the property 'ShopNumber'
        }
        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Test]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Test]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Coupons'
        /// </summary>
        [Test]
        public void CouponsTest()
        {
            // TODO unit test for the property 'Coupons'
        }

    }

}
