/* 
 * ws-treasure
 *
 * tresure api
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserInfoTests
    {
        // TODO uncomment below to declare an instance variable for UserInfo
        //private UserInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserInfo
            //instance = new UserInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserInfo
        /// </summary>
        [Test]
        public void UserInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserInfo
            //Assert.IsInstanceOfType<UserInfo> (instance, "variable 'instance' is a UserInfo");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'Birthdate'
        /// </summary>
        [Test]
        public void BirthdateTest()
        {
            // TODO unit test for the property 'Birthdate'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'Postalcode'
        /// </summary>
        [Test]
        public void PostalcodeTest()
        {
            // TODO unit test for the property 'Postalcode'
        }
        /// <summary>
        /// Test the property 'InRelation'
        /// </summary>
        [Test]
        public void InRelationTest()
        {
            // TODO unit test for the property 'InRelation'
        }
        /// <summary>
        /// Test the property 'AmountChildren'
        /// </summary>
        [Test]
        public void AmountChildrenTest()
        {
            // TODO unit test for the property 'AmountChildren'
        }

    }

}
